<template>
  <div class="table-page sources-page">
    <div class="page-toolbar">
      <el-tag type="primary">{{ regionName }}</el-tag>
      <el-button type="primary" icon="el-icon-plus" @click="openCreate">新增排放源</el-button>
      <el-button type="success" icon="el-icon-check" @click="enableAll">全部启用</el-button>
      <el-button type="warning" icon="el-icon-close" @click="disableAll">全部停用</el-button>
      <el-button type="danger" icon="el-icon-delete" :disabled="selected.length===0" @click="removeSelected">批量删除 ({{ selected.length }})</el-button>
      <span class="spacer" />
      <span>过滤：</span><el-select v-model="draftFilterType" style="width:140px"><el-option value="" label="全部类型"/><el-option v-for="t in sourceTypes" :key="t.value" :value="t.value" :label="t.label"/></el-select><el-button @click="applyTypeFilter">确定</el-button>
      <el-button type="text" icon="el-icon-refresh" @click="refresh">刷新</el-button>
    </div>
    <div class="table-shell"><el-table v-loading="loading" :data="filteredItems" border stripe row-key="id" @selection-change="selected=$event"><el-table-column type="selection" width="46"/><el-table-column prop="id" label="ID" width="60"/><el-table-column prop="name" label="名称"/><el-table-column label="类型" width="100"><template slot-scope="s"><el-tag size="small">{{ labelOf(s.row.sourceType) }}</el-tag></template></el-table-column><el-table-column prop="latitude" label="纬度"/><el-table-column prop="longitude" label="经度"/><el-table-column label="污染物"><template slot-scope="s"><el-tag v-for="p in s.row.pollutants" :key="p.id" size="mini" style="margin-right:4px">{{ p.pollutantType }}: {{ pollutantValue(s.row,p) }}</el-tag><span v-if="!s.row.pollutants.length" class="muted">—</span></template></el-table-column><el-table-column label="启用" width="90"><template slot-scope="s"><el-switch v-model="s.row.isActive" @change="setActive(s.row,$event)"/></template></el-table-column><el-table-column label="操作" width="130"><template slot-scope="s"><el-button type="text" size="small" @click="openEdit(s.row)">编辑</el-button><el-button type="text" size="small" style="color:#f56c6c" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table></div>
    <el-dialog :visible.sync="dialogVisible" :title="dialogMode==='create'?'新增排放源':'编辑排放源'" width="620px"><el-form label-width="110px"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.sourceType"><el-radio-button v-for="t in sourceTypes" :key="t.value" :label="t.value">{{ t.label }}</el-radio-button></el-radio-group></el-form-item><el-form-item label="纬度"><el-input-number v-model="form.latitude" :precision="6"/></el-form-item><el-form-item label="经度"><el-input-number v-model="form.longitude" :precision="6"/></el-form-item><el-form-item label="高度"><el-input-number v-model="form.height"/></el-form-item><el-form-item label="是否启用"><el-switch v-model="form.isActive"/></el-form-item></el-form><span slot="footer"><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></span></el-dialog>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'; import { sourcesApi } from '@/api'; import type { EmissionSource } from '@/types'
const sourceTypes=[{value:'point',label:'点源'},{value:'area',label:'面源'},{value:'equivalent_area',label:'等效面源'},{value:'line',label:'线源'}]
export default Vue.extend({ name:'SourcesView', data:()=>({ items:[] as EmissionSource[], loading:false, selected:[] as EmissionSource[], sourceTypes, draftFilterType:'', appliedFilterType:'', dialogVisible:false, dialogMode:'create', editId:null as number|null, form:{ name:'', sourceType:'point', latitude:39.9, longitude:116.4, height:50, markerSymbol:'factory', markerColor:'#FF5722', isActive:true, pollutants:[] as any[] } as any }), computed:{ regionName():string{ return this.$store.state.regions.find((r:any)=>r.key===this.$store.state.currentRegionKey)?.name || '' }, filteredItems():EmissionSource[]{ return this.appliedFilterType ? this.items.filter(i=>i.sourceType===this.appliedFilterType) : this.items } }, mounted(){ this.refresh() }, methods:{ labelOf(t:string){return sourceTypes.find(x=>x.value===t)?.label || t}, pollutantValue(row:any,p:any){return row.sourceType==='equivalent_area'&&p.concentration!=null?p.concentration:p.emissionRate}, async refresh(){this.loading=true; try{this.items=await sourcesApi.list(0,1000,this.$store.state.currentRegionKey); this.selected=[]} finally{this.loading=false}}, openCreate(){this.dialogMode='create';this.editId=null;Object.assign(this.form,{name:'',sourceType:'point',latitude:39.9,longitude:116.4,height:50,isActive:true,pollutants:[]});this.dialogVisible=true}, openEdit(row:EmissionSource){this.dialogMode='edit';this.editId=row.id;Object.assign(this.form,{...row,pollutants:row.pollutants.map(p=>({pollutantType:p.pollutantType,emissionRate:p.emissionRate,concentration:p.concentration}))});this.dialogVisible=true}, async submit(){ if(this.dialogMode==='create') await sourcesApi.create(this.form,this.$store.state.currentRegionKey); else if(this.editId) await sourcesApi.update(this.editId,this.form); this.dialogVisible=false; this.refresh() }, async setActive(row:EmissionSource,isActive:boolean){await sourcesApi.update(row.id,{isActive});this.refresh()}, async enableAll(){await Promise.all(this.items.filter(i=>!i.isActive).map(i=>sourcesApi.update(i.id,{isActive:true})));this.refresh()}, async disableAll(){await Promise.all(this.items.filter(i=>i.isActive).map(i=>sourcesApi.update(i.id,{isActive:false})));this.refresh()}, applyTypeFilter(){this.appliedFilterType=this.draftFilterType;this.selected=[]}, async remove(row:EmissionSource){await sourcesApi.delete(row.id);this.refresh()}, async removeSelected(){await Promise.all(this.selected.map(r=>sourcesApi.delete(r.id)));this.selected=[];this.refresh()} } })
</script>
