// <auto-generated />
using System;
using GnnSimulation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GnnSimulation.Data.Migrations
{
    [DbContext(typeof(GnnDbContext))]
    [Migration("20260618024236_AddFixedRegions")]
    partial class AddFixedRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GnnSimulation.Data.Entities.EmissionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("AreaHeight")
                        .HasColumnType("REAL")
                        .HasColumnName("area_height");

                    b.Property<double?>("AreaLength")
                        .HasColumnType("REAL")
                        .HasColumnName("area_length");

                    b.Property<string>("AreaShape")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("area_shape");

                    b.Property<double?>("AreaTemperature")
                        .HasColumnType("REAL")
                        .HasColumnName("area_temperature");

                    b.Property<double?>("AreaWidth")
                        .HasColumnType("REAL")
                        .HasColumnName("area_width");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Diameter")
                        .HasColumnType("REAL")
                        .HasColumnName("diameter");

                    b.Property<double?>("EndLat")
                        .HasColumnType("REAL")
                        .HasColumnName("end_lat");

                    b.Property<double?>("EndLon")
                        .HasColumnType("REAL")
                        .HasColumnName("end_lon");

                    b.Property<double>("Height")
                        .HasColumnType("REAL")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double?>("LineHeight")
                        .HasColumnType("REAL")
                        .HasColumnName("line_height");

                    b.Property<double?>("LineSegmentLength")
                        .HasColumnType("REAL")
                        .HasColumnName("line_segment_length");

                    b.Property<double?>("LineTemperature")
                        .HasColumnType("REAL")
                        .HasColumnName("line_temperature");

                    b.Property<string>("LineType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("line_type");

                    b.Property<double?>("LineWidth")
                        .HasColumnType("REAL")
                        .HasColumnName("line_width");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("MarkerColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("marker_color");

                    b.Property<string>("MarkerSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("marker_symbol");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double?>("SigmaZ0Area")
                        .HasColumnType("REAL")
                        .HasColumnName("sigma_z0_area");

                    b.Property<double?>("SigmaZ0Line")
                        .HasColumnType("REAL")
                        .HasColumnName("sigma_z0_line");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<double?>("StartLat")
                        .HasColumnType("REAL")
                        .HasColumnName("start_lat");

                    b.Property<double?>("StartLon")
                        .HasColumnType("REAL")
                        .HasColumnName("start_lon");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Velocity")
                        .HasColumnType("REAL")
                        .HasColumnName("velocity");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_emission_sources_id");

                    b.ToTable("emission_sources", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.MarkerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_marker_configs_id");

                    b.ToTable("marker_configs", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.Meteorology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("BoundaryLayerHeight")
                        .HasColumnType("REAL")
                        .HasColumnName("boundary_layer_height");

                    b.Property<double?>("CloudCover")
                        .HasColumnType("REAL")
                        .HasColumnName("cloud_cover");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("Humidity")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("REAL")
                        .HasColumnName("precipitation");

                    b.Property<DateTime>("RecordTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("record_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("StabilityClass")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("stability_class");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("WindDirection")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_direction");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("wind_speed");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_meteorology_id");

                    b.ToTable("meteorology", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.PollutantEmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("Concentration")
                        .HasColumnType("REAL")
                        .HasColumnName("concentration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("EmissionRate")
                        .HasColumnType("REAL")
                        .HasColumnName("emission_rate");

                    b.Property<string>("PollutantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("pollutant_type");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_pollutant_emissions_id");

                    b.HasIndex("SourceId");

                    b.ToTable("pollutant_emissions", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.Receptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("Height")
                        .HasColumnType("REAL")
                        .HasColumnName("height");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("MarkerColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("marker_color");

                    b.Property<string>("MarkerSymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("marker_symbol");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_receptors_id");

                    b.ToTable("receptors", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionEmissionSource", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_id");

                    b.HasKey("RegionId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("region_sources", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionMeteorology", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<int>("MeteorologyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meteorology_id");

                    b.HasKey("RegionId", "MeteorologyId");

                    b.HasIndex("MeteorologyId");

                    b.ToTable("region_meteorology", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionReceptor", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("region_id");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receptor_id");

                    b.HasKey("RegionId", "ReceptorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("region_receptors", (string)null);
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.PollutantEmission", b =>
                {
                    b.HasOne("GnnSimulation.Data.Entities.EmissionSource", "Source")
                        .WithMany("Pollutants")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionEmissionSource", b =>
                {
                    b.HasOne("GnnSimulation.Data.Entities.Region", "Region")
                        .WithMany("Sources")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GnnSimulation.Data.Entities.EmissionSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionMeteorology", b =>
                {
                    b.HasOne("GnnSimulation.Data.Entities.Meteorology", "Meteorology")
                        .WithMany()
                        .HasForeignKey("MeteorologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GnnSimulation.Data.Entities.Region", "Region")
                        .WithMany("Meteorologies")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meteorology");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.RegionReceptor", b =>
                {
                    b.HasOne("GnnSimulation.Data.Entities.Receptor", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GnnSimulation.Data.Entities.Region", "Region")
                        .WithMany("Receptors")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receptor");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.EmissionSource", b =>
                {
                    b.Navigation("Pollutants");
                });

            modelBuilder.Entity("GnnSimulation.Data.Entities.Region", b =>
                {
                    b.Navigation("Meteorologies");

                    b.Navigation("Receptors");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
